sudo: required

services:
  - docker

env:
  global:
    - secure: "nQdC5nGHfVUgoFaTN9HaCGminFgiIFXSbK7sSlBasVLrChVVRB0UZKtTnhavgiNa9rnCSIFHWiIJTZHkM+58fOzT8XGE/+YNr3klhLGoiNSTO7kgHc9+q07J7QGdoyfqTy5IJg7QXwgS3CYOan6W7L8WHy/Ms6LpsPm+ZeqOu1b2Fbqev/Agga+UJU1du5iuaAnFCo5CdpB1pIQ21YPAUh4CuVsXeJUAiF8wqAjTs1Mse4iLP4peQjpvyzQf2GX3zHv3Jbx7aG4raN26nD8i9z+janRTMbFTd33yG/sUGOF5EZ/kkUh2RIrHGD9UfpImVjD3pj5ghJ+ojWkG27sbLVmEiaptb+n/B3SAGznivlLxUllSiylcpJ1/MRz6DB0N4EcroxPpDfmnlaFz6WZbdtRURA83gOXeLRWKQZPLWBbHwyqZDXdyb08As5tMlchTdyw1r4Au61HOTtrw9h/zJCdsV+T2echDZcEqdZd3WoIyyZQZdoFRuoKPIcTN/uaL71mCfpswPVQ3YdflJtkc1zTQxhQomb9PUJZgKI2b+tagz/lpBMHjMpjQxJnOdHLto/pbauvi38kC6VPJiwClQ8mTsibWhPovTI0DmT3OjwbLUnCqo3AsMdu1QDu7uqGszfH/pwQwQ9yufmlNkEUmvgSPGD4YxWUVRVkjb4u/mFs="  # DOCKER_EMAIL
    - secure: "trVeaDBFRK8D5GSWbpc5XkQaaYcDAMZkk7vOjrPHAP9igrsYe9NBioSwE6QGJnbS25Wy1HC14MYcXZReF+RR3zVN69xiDREwAS+56TC05FYc6LOrITx42mEZZ59ud30bLg6Gk70OHE/0szclmXhIGLyDw4Tn9UMfk//RO5xU75ZHQapNrVyXC4WkdrxsXxgimef3j8liU/otjZAZ+Wt3n3rSMYzFfygflsIMtPtwk7MSjCuO7ACLic8t05rpA+4MeddT9uJxIetuoL1CUSy6jJjNzvU3hCOA537taUGJsmXyDrrl2vVWJDJdzDoUglLSGKQy/aG6exGQu2LYHnnX97LbRpl+Q9GNek2fCYLUFMafFBA1QAJyTUvaZDLNs/QvPxohMRitHuaX+wvAlgTOvkJKziK7RTBDg+nYC3c2xES273vMqOyHb994yK0Uja6/1jA8AA5KmVNVDvaMEDDRRafYS5sdlVuH5o+jl99O20MPUp/1ffIrQl37EW1C8S2NCxhInz6ObhXl84BcYeNIyrF4vtaZOZVcjaLepxgyzQxqRFJoBBClSwmuO8JrwPhHRGex1onhbJB5LUx+BMzDwRZdozgv8kvK1xVFfXFFwYvSN3x0V+iacT7GnHooBfYa5yee4/hjRTLVRK8bFSpDi9gJerdSB7fopUJFwH/ZPq0="
    - secure: "rF42ianm232JnTJ2/hrIAnM7jVV45xEh7zdb8rt6xlCiKBP6k+k8qXaMIi1/Mdlc3jSluRRn6d/n0QOVGaGgESW34xRYeuQTwePRQXOA7N6MKTjzblYqR9DbA5DqO1Bm8hAj66gwBlNJ45gTDRsKxvQvEQYC7Ga5AS0GVu0fiRXbQ7CMZI2JmfvmZk1d1T033V5n+Dqxz+4ZtAe55lAW1bkOWFoAcvwMw9Ou7JUL96kFhjJgy3C/Yh2RrELfr4VusapgmjaVWSG5DzeYGE3XNBsd68quT4O+CxQYBuxhztWED6SVGMYSTqjTrmhcUAFn+lU43f/XcQPRTyOBoudCPjnEjFlRz+Wt7FjiIr5CxPQN3PK+jXu8mTgvwIn7BDU+wNksBLNKej5UyndxgN1xNZNFiRUq5kcyWJCn8NvWmUN82asnghHq2IHg4Nssl95eLbmN1gUCjHu50suzoqY0ZFMY+sCq+/YIbK9u6CCTgiWOEnm1xYJMqOFKSZDGCBlWMB+6Uo/czrBy6ZbYXKNVct+K3Y6evuyzEx3FbHsYfGM+23I2qFItJ9HL+X7RLgV/yvghiV8NJ2T0ec7hm/2VpKRv9f83M333dnkd3dNiPLn5fAVNwudhklt2odz1ihOWpBL4NupzYik0TMyJjMX2NrCuFW5dQkvCJXZtU1Xu3Ic="
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - echo "fake build..."
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t typhoon1986/testbuild .
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push typhoon1986/testbuild;
    fi
